CREATE TABLE TC_INPUT_MAPPING_MATRIX_HDR 
(
  HDR_ID NUMBER(16, 0) NOT NULL 
, FUNCTIONALITY_CODE VARCHAR2(150 CHAR) 
, FUNCTIONALITY_DESC VARCHAR2(150 CHAR) 
, SCENARIO_CODE VARCHAR2(150 CHAR) 
, SCENARIO_DESC VARCHAR2(150 CHAR) 
, MODULE_CODE VARCHAR2(150 CHAR) 
, RELEASE_NO VARCHAR2(150 CHAR) 
, ACTIVE_FLAG VARCHAR2(1 CHAR) 
, USER_ID VARCHAR2(150 CHAR) 
, TEST_DATA_GENERATED VARCHAR2(1 CHAR) 
, TEST_CASES_GENERATED VARCHAR2(1 CHAR) 
, CONSTRAINT SYS_C009778026 PRIMARY KEY 
  (
    HDR_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE TC_INPUT_MAPPING_MATRIX_HDR
ADD CONSTRAINT TIMMH_UK1 UNIQUE 
(
  FUNCTIONALITY_CODE 
, SCENARIO_CODE 
, MODULE_CODE 
, RELEASE_NO 
)
ENABLE;
